### ISSUE TITLE
Memory leak out there somewhere

### ISSUE THREAD

**Issue by BigMeatyClaws** [LeapLabTHU/Agent-Attention#1]
Managed to eek out only 1 768x1024 picture before it starts demanding 9GB RAM on saving the picture.

**Comment by tian-qing001** [comment]
Hi @BigMeatyClaws, a more detailed description of the specific problem you are encountering is needed. The information provided thus far lacks sufficient detail for us to offer meaningful assistance.

**Comment by BigMeatyClaws** [comment]
> a more detailed description of the specific problem you are encountering is needed.

Wish I could help, but it seems very random. I'm just letting you know the problem exists. If I figure out how to replicate it, I'll be sure to drop it here.

**Comment by tian-qing001** [comment]
Hi @BigMeatyClaws, we have addressed a minor issue related to the usage of AgentSD, which might be connected to the problem you're currently facing.
