### ISSUE TITLE
注意力的维度

### ISSUE THREAD

**Issue by Eight3H** [LeapLabTHU/Agent-Attention#13]
你好，作者，如果我现在不仅有h,w   ，还有一个d   ，作者有没有考虑过这方面，请您联系我www.756233138@foxmail.com

**Comment by Eight3H** [comment]
只针对 Agentattention那快的代码，注意力偏置

**Comment by tian-qing001** [comment]
Hi @Eight3H, please provide more details regarding your question.

**Comment by Eight3H** [comment]
self.ah_bias = nn.Parameter(torch.zeros(1, num_heads, agent_num, window_size[0], 1))
            self.aw_bias = nn.Parameter(torch.zeros(1, num_heads, agent_num, 1, window_size[1]))
            self.ha_bias = nn.Parameter(torch.zeros(1, num_heads, window_size[0], 1, agent_num))
            self.wa_bias = nn.Parameter(torch.zeros(1, num_heads, 1, window_size[1], agent_num))
你的注意力偏置是这样的，现在我不止有h和w,还有d也就是处理的是3d的   该怎么处理，有考虑过吗

**Comment by tian-qing001** [comment]
It's essential to provide a clear and detailed description of your problem, avoiding assumptions about my understanding of the specific area and task you are addressing. If you are denoting **depth** by 'd', consider expanding the dimensions of agent bias and treating it similarly to `height` and `width`. If 'd' represents **dimension**, treat it in a manner analogous to `num_heads`.

**Comment by Eight3H** [comment]
是深度

**Comment by Eight3H** [comment]
the  total  model's input size  is   (1,4,128,128,128),1 represent  batchsize, 4 represent channel   ，128 represent   h,w,d respectively，i   read   your  Appendix A  about  Agent Bias,you say  Each position offset is composed of three parameters， ssuch as  B1 = (B′1c + B′1r + B′1b),include  column bias B1c ∈ Rn×1×w, row bias B1r ∈ Rn×h×1 and block bias B1b ∈ Rn×h0×w0,but  now  have   d  this dimension,how can i  modify  the   agent bias    ,  should   i    add  a  new  parameter   ? like  B1c      B1r   B1b   and B1d,can  you  give me some addvice ,waiting for your reply

**Comment by Jaywxy** [comment]
> 是深度

请问一下你实现了这个注意力在3D上的使用吗？
