### ISSUE TITLE
AgentSD implementation based on TensorFlow

### ISSUE THREAD

**Issue by ZTzxj** [LeapLabTHU/Agent-Attention#15]
Hi, I would like to ask if my network is built using the tensorflow framework for stable diffusion, this is the code for it https://github.com/keras-team/keras-cv/blob/master/keras_cv/models/stable_ diffusion/stable_diffusion.py, I want to add your agent attention to this network, but it seems that since the example you gave is also a stable diffusion built using pytorch, it reports an error when I add it to my network. ?

**Comment by tian-qing001** [comment]
Hi @ZTzxj, thank you for your interest in our work. Currently, we do not have immediate plans to offer an AgentSD implementation based on TensorFlow. However, we encourage and welcome contributions from the community to explore and achieve this.
