### ISSUE TITLE
How is it used for the backbone of the Siamese tracking network?

### ISSUE THREAD

**Issue by C-C-Y** [LeapLabTHU/Agent-Attention#16]
May I ask how this can be applied to a Siamese tracking network where the input images are of different sizes and serve as a backbone for weight sharing?  I noticed that the agent_num and window parameters are related to the input image size, how can I set them to apply to different input image sizes at the same time?

**Comment by tian-qing001** [comment]
Hi @C-C-Y, the `agent_num` is a predetermined hyperparameter, remaining constant regardless of image resolution. If you wish to support variable sized image input, consider modifying the relevant code and dynamically interpolating model parameters, such as `pos_embed`, to align with current image sizes. This adaptation has already been implemented in our code for detection and segmentation tasks, and you can find reference implementation there.
