### ISSUE TITLE
Agent bias

### ISSUE THREAD

**Issue by Eight3H** [LeapLabTHU/Agent-Attention#19]
the total model's input size is (1,4,128,128,128),1 represent batchsize, 4 represent channel ，128 represent h,w,d respectively，i read your Appendix A about Agent Bias,you say Each position offset is composed of three parameters， ssuch as B1 = (B′1c + B′1r + B′1b),include column bias B1c ∈ Rn×1×w, row bias B1r ∈ Rn×h×1 and block bias B1b ∈ Rn×h0×w0,but now have d this dimension,how can i modify the agent bias , should i add a new parameter ? like B1c B1r B1b and B1d,can you give me some addvice ,waiting for your reply

**Comment by tian-qing001** [comment]
Expand the dimensions of agent bias and treat depth similarly to height and width, i.e., $B_{1r}\in\mathbb{R}^{n \times h \times 1 \times 1}$, $B_{1c}\in\mathbb{R}^{n \times 1 \times w \times 1}$, $B_{1d}\in\mathbb{R}^{n \times 1 \times 1 \times d}$, $B_{1b}\in\mathbb{R}^{n \times h_0 \times w_0 \times d_0}$.

**Comment by Eight3H** [comment]
Thanks    for  your  reply, i will try  like  it
