### ISSUE TITLE
Training on a single GPU

### ISSUE THREAD

**Issue by YEKAI-2022** [LeapLabTHU/Agent-Attention#2]
你好，我在本机debug代码时，出现并行的问题local_rank和world_size,是参数设置有错误吗？

![Snipaste_2023-12-20_16-07-49](https://github.com/LeapLabTHU/Agent-Attention/assets/130537009/d63f1011-012e-46ce-ac69-67646f224d9e)

**Comment by YEKAI-2022** [comment]
我本机是单机单卡的，像这种debug出现并行问题该怎么解决，

**Comment by tian-qing001** [comment]
Hello @YEKAI-2022. For training our module on a single GPU, the recommended command is:

```bash
python -m torch.distributed.launch --nproc_per_node=1 main.py --cfg <path-to-config-file> --data-path <imagenet-path> --output <output-path>
```

Upon reviewing the screenshot you shared, it appears that the command you are currently using is functionally equivalent to:

```bash
python main.py --cfg <path-to-config-file> --data-path <imagenet-path> --output <output-path>
```

**Comment by tian-qing001** [comment]
If your objective is solely to debug the model, consider creating a new script where you can load the model without executing the `main.py`.

**Comment by YEKAI-2022** [comment]
torch.distributed.launch --nproc_per_node=1如果debug的话，上述的参数也要和--cfg <path-to-config-file> --data-path <imagenet-path> --output <output-path>加到参数列表吗

**Comment by tian-qing001** [comment]
You can refer to sections 3.2 and 3.3 of [this blog](https://blog.csdn.net/yang332233/article/details/131957972). It's important to note that these settings are not exclusive to our project and can be found online.

**Comment by YEKAI-2022** [comment]
Thank you very much for your answer
