### ISSUE TITLE
Agent_num

### ISSUE THREAD

**Issue by Dasha484** [LeapLabTHU/Agent-Attention#20]
Hello, I encountered several questions while reading your code.

1.What does 'agent_num mean'? I did not find a clear definition in the paper.

2.When defining bias, why is the dimension of bias related to agent_num? If I modify agent_num, it will result in dimension mismatch. However, I noticed that your paper includes comparisons with different agent_num.

I hope to receive your response.

**Comment by tian-qing001** [comment]
Hi @Dasha484. 
1. `agent_num` represents the number of agent tokens, which has been detailed in the paper. We also provide ablation experiments on it in Table 8. 
2. Various agent tokens exhibit distinct biases across spatial positions, so the dimension of agent bias is related to `agent_num`. When modifying `agent_num`, consider using interpolation to adjust the size of agent bias.
