### ISSUE TITLE
Could you provide codes for calculating FID, Time (s/im), and Memory (GB/im)?

### ISSUE THREAD

**Issue by Doraemonzm** [LeapLabTHU/Agent-Attention#22]
Thanks for your excellent work. I noticed that AgentSD performs better than ToMeSD and Stable Diffusion v1.5. Could you provide codes for calculating FID, Time (s/im), and Memory (GB/im)?

**Comment by tian-qing001** [comment]
Hi @Doraemonzm, thank you for your attention to our work. As described in section B.2, we calculate FID scores employing
[pytorch-fid](https://github.com/mseitzer/pytorch-fid). To assess speed, we calculate the average generation time of all 2,000 samples on a single RTX4090 GPU. GB/img is measured as the total memory usage change when increasing batch size by 1.
