### ISSUE TITLE
pretrained

### ISSUE THREAD

**Issue by mahao535** [LeapLabTHU/Agent-Attention#23]
Is there a pre-training weight that can be downloaded

**Comment by tian-qing001** [comment]
We already provide all pretrained models.
https://github.com/LeapLabTHU/Agent-Attention/tree/master/agent_transformer#pretrained-models
https://github.com/LeapLabTHU/Agent-Attention/tree/master/downstream/detection#results-and-models
https://github.com/LeapLabTHU/Agent-Attention/tree/master/downstream/segmentation#results-and-models
