### ISSUE TITLE
Agent-attention

### ISSUE THREAD

**Issue by john09282922** [LeapLabTHU/Agent-Attention#24]
Hi, I would like to use your model into DDPM or DDIM method. Is it possible?
Could you tell me which code or file is really important to add to them?

**Comment by tian-qing001** [comment]
Hi @john09282922. Agent attention is a plug-in module that can be applied to various Transformer models. We provide example code [here](https://github.com/LeapLabTHU/Agent-Attention/tree/master/agentsd#example) for applying AgentSD to PLMS and DDIM samplers.
