### ISSUE TITLE
meaning and method

### ISSUE THREAD

**Issue by john09282922** [LeapLabTHU/Agent-Attention#25]
Thanks for the information.
I have additional question. 
What is that meaning of remove and apply patch? also sx, sy, ratio? 
agentsd is your model?  
agentsd.remove_patch(self.model)
agentsd.apply_patch(model, sx=4, sy=4, ratio=0.4, agent_ratio=0.95)

actually, I would like to apply your agent attention module to ddim from guided diffusion model.

thanks,
jungmin

**Comment by tian-qing001** [comment]
Hi @john09282922, our code for agentsd is developed on top of [ToMeSD](https://github.com/dbolya/tomesd), where you can refer to the paper for explanations of various variables. The scale value is referenced as `self.scale` in [this line](https://github.com/LeapLabTHU/Agent-Attention/blob/c3889c7cdb00ce33a2cb6852988bb98b9f44f2f2/agentsd/patch.py#L129) and [this line](https://github.com/LeapLabTHU/Agent-Attention/blob/c3889c7cdb00ce33a2cb6852988bb98b9f44f2f2/agentsd/patch.py#L142).
It is not possible to use randomly initialized DWC without training.
