### ISSUE TITLE
Connection with Guided diffusion

### ISSUE THREAD

**Issue by john09282922** [LeapLabTHU/Agent-Attention#28]
Hi, May I ask you for your code part to connect guided diffusion? Because I would like to match your code to guided diffusion, not stable diffusion. I think it will be possible, right? Can you give me some help to match q, k, v, agent to guided diffusion?

thanks,

**Comment by tian-qing001** [comment]
Hi @john09282922, it would be interesting to explore the application of our AgentSD method to guided diffusion, a direction we have not yet explored. Adapting AgentSD to guided diffusion should follow a similar process as adapting to stable diffusion, which you can refer to in our AgentSD code.
