### ISSUE TITLE
attn_type in agent-swin

### ISSUE THREAD

**Issue by linxiaomiku** [LeapLabTHU/Agent-Attention#31]
Hello author, first of all, thank you very much for your work. 
Secondly, I am confused that I found you set attn_type in Agent SwinTransformer function to BBBB in the Agent-swin code and config. Whether this will be code that does not use agent attention in actual running

**Comment by tian-qing001** [comment]
Hi @linxiaomiku, thank you for your interest. The default value of `attn_type` is BBBB, but we specify the value in each cfg file, e.g. [agent_swin_t.yaml](https://github.com/LeapLabTHU/Agent-Attention/blob/master/agent_transformer/cfgs/agent_swin_t.yaml)

**Comment by linxiaomiku** [comment]
Ok, thank you very much for your reply
