### ISSUE TITLE
different image solution for training and testing

### ISSUE THREAD

**Issue by hubhub086** [LeapLabTHU/Agent-Attention#38]
Hi! I am using `agent_swin` model as backbone, but because the image resolution during testing is higher than that during training, there are some errors, so I want to know whether the model can support input with dynamic resolution, and how should I modify it.
Looking forward to your reply.

**Comment by tian-qing001** [comment]
Hi @hubhub086. 
You can interpolate agent bias to adapt to the test resolution, which will fix the problem. Please refer to [here](https://github.com/LeapLabTHU/Agent-Attention/blob/9930788405db8f9110bff2538d3747efc7320007/downstream/segmentation/mmseg/models/backbones/agent_swin.py#L150).

**Comment by hubhub086** [comment]
Thanks a lot🎉
