### ISSUE TITLE
agent-attention是否是在单独的窗口内进行

### ISSUE THREAD

**Issue by lshqi** [LeapLabTHU/Agent-Attention#47]
作者您好，读了您的agent-attention后收获很大，但有个疑问，在进行agent-attention前都会进行窗口的划分，那这样agent-attention都是在窗口内完成的，各窗口的信息并没有被互相学习，这个是否有办法可以解决

**Comment by tian-qing001** [comment]
Hi @lshqi, thanks for your interest in our work.
This is only one window in agent attention. In other words, agent attention employs a global receptive field and does not use the window partition.
