### ISSUE TITLE
感谢您精彩的贡献，想咨询下在实验过程中是否存在对于vision transformer 结构的改进代码模块？

### ISSUE THREAD

**Issue by BJFU-CS2012** [LeapLabTHU/Agent-Attention#9]

**Comment by tian-qing001** [comment]
Hi @BJFU-CS2012, thank you for acknowledging our work, but I could not understand your question.

**Comment by BJFU-CS2012** [comment]
> Hi @BJFU-CS2012, thank you for acknowledging our work, but I could not understand your question.

sry about that. I want to apply agent_attention to the Transformer module in the VIT model, and I need to write my own code at the moment I don't know if you've had any previous work on this for reference.

**Comment by tian-qing001** [comment]
Hello @BJFU-CS2012, we've implemented our agent attention in DeiT, which shares the same model structure as ViT. You can find the details in the [agent_deit.py](https://github.com/LeapLabTHU/Agent-Attention/blob/master/agent_transformer/models/agent_deit.py).

**Comment by BJFU-CS2012** [comment]
Okay, thank you very much for your patience and good luck with your research!
